title: "Operating Systems 2021-1 (OS211)"
description: "This site is used for OS 2021-1"
copyright: "2021"
author: "Cornelita"
address: "Surabaya"
urlweb: "https://cornelita.github.io/os211/"
urlgithub: "https://github.com/cornelita/os211/"
urlghpage: "https://cornelita.github.io/os211/"
